### PR TITLE
Extended

### PR DESCRIPTION
**Pull request by dnagarju**
We're a group of grad students of Carnegie Mellon University, currently pursuing our Masters in Information Security in the Information Networking Institute. For our research project last semester in the Network Security course, we found your paper incredibly interesting and decided to contribute our share to your codebase. We have successfully extended AFLNET locally to include TFTP, NTP,SNMP and DHCP protocols, and tested it against servers with substantial results. We hope to integrate our code with yours, and believe that this extension would be useful to others who wish to fuzz their server implementations for each of the above mentioned protocols.

### CODE REVIEW

**Comment by mboehme** [comment]
Thanks all. This is amazing!

Most of the `memcpy` and `memcmp` (e.g., of size 1) can just be simple assignments or equivalence checks. Otherwise, LGTM.

**Comment by dnagarju** [comment]
Hello Böhme,

Thank you for acknowledging our commit request. We can change those if
needed, we included them as it would help us keep functions similar to the
ones written already. Assuming this would further help folks who would want
to extend the code base. Do let us know if there are any other changes.

Thanks and Regards,
Dharithri Nagarjun
MS'34, MSIS

**Comment by thuanpv** [comment]
This LGTM too. Thanks @dnagarju & team for your great contribution. Thanks @mboehme for doing code review.

**Comment by thuanpv** [comment]
@dnagarju , it would be great if you could contribute further by adding tutorials (https://github.com/aflnet/aflnet/tree/master/tutorials) for fuzzing servers that support the new protocols.

**Comment by dnagarju** [comment]
Hey Team,
Sorry for the delayed response. Will add in the tutorials soon.
Thanks and Regards,
Dharithri Nagarjun
MS'34, MSIS

**Pull request merged**
