### PR TITLE
Added DNS server fuzzing support

### PR DESCRIPTION
**Pull request by amlamarra**
These changes allow AFLNet to fuzz DNS servers. A tutorial is included.

Disclaimer: I've only tested this against Dnsmasq.

### CODE REVIEW

**Comment by thuanpv** [comment]
Thanks @amlamarra for sending this pull request. In your README.md file, you say that "Various DNS queries have been recorded and saved in the aflnet/tutorials/dnsmasq/in-dns directory for seed inputs. If you want to create your own inputs, please follow the tutorial for fuzzing Live555 RTSP server included in the main AFLNet README.md"; however I see only 1 seed input in in-dns. Could you please confirm this and upload other seeds if possible?

**Comment by thuanpv** [comment]
Hi @amlamarra. I tested the integration and it works -- AFLNet finds crashing input and it can be replayed successfully so I merge your changes. Please feel free to send another pull request for additional seeds if you want. Thanks again for your contribution!

**Comment by amlamarra** [comment]
> Thanks @amlamarra for sending this pull request. In your README.md file, you say that "Various DNS queries have been recorded and saved in the aflnet/tutorials/dnsmasq/in-dns directory for seed inputs. If you want to create your own inputs, please follow the tutorial for fuzzing Live555 RTSP server included in the main AFLNet README.md"; however I see only 1 seed input in in-dns. Could you please confirm this and upload the remaining seeds if possible?

I put all of the queries into that single file. Should I separate them? Does AFLNet treat each file as a separate conversation with the server?

I mainly did that because it was easier. I downloaded a sample DNS capture from [wireshark.org](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=dns.cap) and most of the packets in there are considered a single UDP conversation by Wireshark.

**Comment by thuanpv** [comment]
I see. Thank you for your clarification!

**Pull request merged**
