### PR TITLE
Add DICOM protocol

### PR DESCRIPTION
**Pull request by MashaSamoylova**
Hello

I've added [DICOM](https://www.dicomstandard.org/) support for fuzzing.
`extract_requests_dicom` is based on PDU length and `extract_response_codes_dicom` returns response PDU type as response code.
Also, I wrote the tutorial for fuzzing the DICOM server from [dcmtk](https://dicom.offis.de/dcmtk.php.en).

I'm not sure with `return 1;` in `save_if_interesting` function. If it is wrong I will roll back changes.

### CODE REVIEW

**Comment by thuanpv** [comment]
Hello Maria,

Thank you very much for your contribution to AFLNet.

The code changes & tutorial look all good to me. Just a minor thing -- could you please explain to me why did you add "return 1" to save_if_interesting?

Cheers,

Thuan

**Comment by MashaSamoylova** [comment]
Sorry, I was wrong in `save_if_interesting `. I've rolled it back.

**Comment by thuanpv** [comment]
Thanks for your quick reply. I have followed your tutorial on both Ubuntu 16.04 and 18.04 and I faced the same issue while starting the dcmqrscp server (Step-1 Server Setup). I received this error message "F: bad group name dcmtk". Could you please try to fix it? 

There is another (minor) issue. In your tutorial, there is a step to update the configuration file

> Fix paths to COMMON ACME_STORE UNITED_STORE directories in configuration file dcmqrscp.cfg(lines: 79, 80, 81).

However, I could not find the path to COMMON in the configuration file.

**Comment by thuanpv** [comment]
It works well now. I have merged the PR. Thank you very much again for your contribution!

**Comment by MashaSamoylova** [comment]
@thuanpv Thank you for the quick reply. And sorry for that checks of the dcmqrscp server took your time. 

Meanwhile, aflnet has found new crashes in the server 🙂

**Comment by thuanpv** [comment]
Thanks, Maria. Great to know that AFLNet has found new crashes!

**Pull request merged**
